#!/bin/bash
#PBS -A external-rh_rh_gm             # Accounting info
#PBS -N dengen_merge
#PBS -l nodes=1:ppn=64                # 64 cores on one node
#PBS -l mem=512gb                      # 512 GB RAM
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -o /ngc/projects2/gm/people/mauqua/hail-singularity/logs/merge.log
#PBS -e /ngc/projects2/gm/people/mauqua/hail-singularity/logs/merge.err

cd $PBS_O_WORKDIR

echo "Merging all shards on $(hostname)..."

# Spark configuration
export PYSPARK_SUBMIT_ARGS="\
--driver-memory 128G \
--executor-memory 128G \
--conf spark.executor.cores=16 \
--conf spark.executor.instances=2 \
--conf spark.sql.shuffle.partitions=512 \
pyspark-shell"

# Run Hail inside Singularity
singularity exec \
  --env PYSPARK_SUBMIT_ARGS="$PYSPARK_SUBMIT_ARGS" \
  --bind /ngc/projects2/gm/people/mauqua/hail-singularity/src:/src \
  --bind /ngc/projects2/gm/people/mauqua/hail-singularity/results:/results \
  --bind /ngc/projects2/gm/people/mauqua/hail-singularity/config:/config \
  --bind /ngc/projects2/gm/people/mauqua/hail-singularity/tmp:/tmp \
  /ngc/projects2/gm/people/mauqua/hail-singularity/container/hail_0.2.136-py3.13.sif \
  python3 /src/merge/dengen_merge.py
